# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b85f2137531e43221afd93288b2a2d35536a7e6fa88752202feb18be4ef6b0ab9d53dec47ca1a7b01dae831db8e74673072937f8e8f1c220f77609260bf016f

test:
  secret_key_base: b9d1384cb0478d460da11f9013bc73befa1d24b57646c1d4434f28bd08e479b5827bb5ed3f0321c5c35bd8ef6c0956e32b9150aed1d97aa6317a957634fb02b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
